import type { L } from "@/lib/i18n";

/**
 * ─────────────────────────────────────────────────────────────
 *  COLOPHON — "cómo está hecho". Meta-content about the site itself:
 *  the stack, the decisions behind it and a few numbers. Bilingual.
 * ─────────────────────────────────────────────────────────────
 */

/** The tools, grouped by role. `note` explains what each one does here. */
export const STACK: { role: L; name: string; note: L }[] = [
  {
    role: { es: "Framework", en: "Framework" },
    name: "Next.js 15",
    note: {
      es: "App Router, generación estática y metadata.",
      en: "App Router, static generation and metadata.",
    },
  },
  {
    role: { es: "UI", en: "UI" },
    name: "React 19",
    note: {
      es: "Componentes propios, cero librerías de componentes.",
      en: "Hand-built components, zero component libraries.",
    },
  },
  {
    role: { es: "Lenguaje", en: "Language" },
    name: "TypeScript",
    note: {
      es: "Tipado estricto de punta a punta.",
      en: "Strict typing end to end.",
    },
  },
  {
    role: { es: "Estilos", en: "Styling" },
    name: "Tailwind CSS v4",
    note: {
      es: "Tokens de diseño y utilidades, sin CSS suelto.",
      en: "Design tokens and utilities, no loose CSS.",
    },
  },
  {
    role: { es: "Animación", en: "Motion" },
    name: "GSAP",
    note: {
      es: "ScrollTrigger y Observer mueven el deck y las transiciones.",
      en: "ScrollTrigger and Observer drive the deck and transitions.",
    },
  },
  {
    role: { es: "Tipografía", en: "Type" },
    name: "Anton · Archivo · Plex Mono",
    note: {
      es: "Display, texto y datos, servidas con next/font.",
      en: "Display, body and data, served with next/font.",
    },
  },
  {
    role: { es: "Infra", en: "Infra" },
    name: "Vercel",
    note: {
      es: "Hosting, Analytics y Speed Insights.",
      en: "Hosting, Analytics and Speed Insights.",
    },
  },
  {
    role: { es: "Contacto", en: "Contact" },
    name: "Web3Forms",
    note: {
      es: "Formulario que envía correo sin backend.",
      en: "Form that emails without a backend.",
    },
  },
];

/** The decisions behind the build — the "why", not just the "what". */
export const DECISIONS: { title: L; note: L }[] = [
  {
    title: { es: "Bilingüe de raíz", en: "Bilingual from the ground up" },
    note: {
      es: "Todo el contenido vive como { es, en } y se cambia en el cliente sin recargar la página.",
      en: "All content lives as { es, en } and switches on the client with no reload.",
    },
  },
  {
    title: {
      es: "Deck en desktop, scroll en móvil",
      en: "Deck on desktop, scroll on mobile",
    },
    note: {
      es: "En pantallas grandes la home es una presentación a pantalla completa; en táctil o con movimiento reducido, scroll normal. Mejora progresiva.",
      en: "On big screens the home is a full-page deck; on touch or reduced-motion, plain scroll. Progressive enhancement.",
    },
  },
  {
    title: { es: "Contenido dirigido por datos", en: "Data-driven content" },
    note: {
      es: "Proyectos, blog y textos viven en /data, separados de la UI: editar el sitio no requiere tocar componentes.",
      en: "Projects, blog and copy live in /data, apart from the UI: editing the site never means touching components.",
    },
  },
  {
    title: { es: "Paleta mínima", en: "Minimal palette" },
    note: {
      es: "Tres colores: tinta, papel y verde ácido. El acento se usa con cuentagotas, nunca como decoración.",
      en: "Three colors: ink, paper and acid green. The accent is used with an eyedropper, never as decoration.",
    },
  },
  {
    title: { es: "Movimiento con propósito", en: "Motion with purpose" },
    note: {
      es: "Cada animación respeta prefers-reduced-motion y se limita a transform y opacity.",
      en: "Every animation respects prefers-reduced-motion and sticks to transform and opacity.",
    },
  },
  {
    title: { es: "Rendimiento como UX", en: "Performance as UX" },
    note: {
      es: "Fuentes con subsetting, imágenes optimizadas, favicon de 3 KB y code splitting por ruta.",
      en: "Subset fonts, optimized images, a 3 KB favicon and route-level code splitting.",
    },
  },
  {
    title: { es: "SEO técnico por código", en: "Technical SEO in code" },
    note: {
      es: "sitemap, robots, JSON-LD, imágenes OG dinámicas y feed RSS, todo generado por el propio Next.",
      en: "sitemap, robots, JSON-LD, dynamic OG images and an RSS feed, all generated by Next itself.",
    },
  },
  {
    title: { es: "Accesibilidad", en: "Accessibility" },
    note: {
      es: "Foco visible, HTML semántico, contraste cuidado y navegación por teclado en el deck.",
      en: "Visible focus, semantic HTML, careful contrast and keyboard navigation in the deck.",
    },
  },
];

/** A few numbers, in the same spirit as the project results. */
export const FACTS: { metric: string; label: L }[] = [
  { metric: "3", label: { es: "Colores en la paleta", en: "Colors in the palette" } },
  { metric: "es / en", label: { es: "Bilingüe completo", en: "Fully bilingual" } },
  { metric: "0", label: { es: "Librerías de componentes", en: "Component libraries" } },
  { metric: "100%", label: { es: "TypeScript", en: "TypeScript" } },
];
